language: python
python:
  - "3.6"
  - "3.7"

jobs:
  include:
    - stage: test
      script:
       - pip install -r requirements.txt
       - python3 -m unittest tests/*.py
    
    - stage: build
      script:
       - python3 setup.py build
       - python setup.py install
